# Generated by Django 4.0.2 on 2026-04-01 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_capacity_flight_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(default='', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Passport must be 2 uppercase letters followed by 6 digits (e.g. AB123456).', regex='^[A-Z]{2}\\d{6}$')]),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_class',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First Class')], default='ECONOMY', max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
