# Generated by Django 4.0.2 on 2026-04-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passenger_email_passenger_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
