# Generated by Django 4.0.2 on 2026-04-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=8),
        ),
    ]
